interfaces = {"sw1": [{'access_vlan': '41',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/1',
  'mode': 'down',
  'native_vlan': '41',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': '41,43',
  'voice_vlan': '20'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/5',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/6',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/7',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/8',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/9',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/10',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/11',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/12',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/13',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/14',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/15',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/16',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/17',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/18',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/19',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/20',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/21',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/22',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/23',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/24',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/1',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/2',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/3',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/4',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/1',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/2',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/3',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/4',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/5',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/6',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/7',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/8',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Fo1/1/1',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Fo1/1/2',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Twe1/1/1',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''},
 {'access_vlan': '',
  'admin_mode': 'dynamic auto',
  'interface': 'Twe1/1/2',
  'mode': '',
  'native_vlan': '',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': '',
  'trunking_vlans': '',
  'voice_vlan': ''}],
"sw2": [{'access_vlan': '41',
  'admin_mode': 'static access',
  'interface': 'Fa1/0/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'Off',
  'trunking_vlans': 'ALL',
  'voice_vlan': '20'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/5',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/6',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/7',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/8',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/9',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/10',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/11',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/12',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/13',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/14',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/15',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/16',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/17',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/18',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/19',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/20',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/21',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/22',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Fa1/0/23',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Fa1/0/24',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'}],
"sw3": [{'access_vlan': '41',
  'admin_mode': 'static access',
  'interface': 'Gi1/0/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'Off',
  'trunking_vlans': 'ALL',
  'voice_vlan': '20'},
 {'access_vlan': '345',
  'admin_mode': 'static access',
  'interface': 'Gi1/0/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'Off',
  'trunking_vlans': 'ALL',
  'voice_vlan': '20'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/5',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/6',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/7',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/8',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/9',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/10',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/11',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/12',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/13',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/14',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/15',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/16',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/17',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/18',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/19',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/20',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/21',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/22',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/23',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/24',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/25',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/26',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/27',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/28',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/29',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/30',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/31',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/32',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/33',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/34',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/35',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/36',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/37',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/38',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/39',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/40',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/41',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/42',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/43',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/44',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/45',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/46',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/47',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/48',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': '20,36,41,43,345',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'}],
"sw4": [{'access_vlan': '41',
  'admin_mode': 'static access',
  'interface': 'Gi1/0/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'Off',
  'trunking_vlans': 'ALL',
  'voice_vlan': '20'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/5',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/6',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/7',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/8',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/9',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/10',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/11',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/12',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/13',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/14',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/15',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/16',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/17',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/18',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/19',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/20',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/21',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/22',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'trunk',
  'interface': 'Gi1/0/23',
  'mode': 'trunk',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/0/24',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/3',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Gi1/1/4',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/1',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'},
 {'access_vlan': '1',
  'admin_mode': 'dynamic auto',
  'interface': 'Te1/1/2',
  'mode': 'down',
  'native_vlan': '1',
  'switchport': 'Enabled',
  'switchport_monitor': '',
  'switchport_negotiation': 'On',
  'trunking_vlans': 'ALL',
  'voice_vlan': 'none'}]}

count = 0 
for sw, intfs in interfaces.items():
    count += 1
    print(sw)

print(count)