---
switches:
  platform: cisco_ios
  port: 22
  data:
    C3750V2:
      upgrade_version: '12.2(55)SE12'
      upgrade_img: 'c3750-ipservicesk9-tar.122-55.SE12.tar'
    C3750X:
      upgrade_version: '15.2(4)E9'
      upgrade_img: 'c3750e-universalk9-tar.152-4.E9.tar'
    C3650:
      upgrade_version: '16.9.4'
      upgrade_img: 'cat3k_caa-universalk9.16.09.04.SPA.bin'
    C9300:  
      upgrade_version: '16.9.4'
      upgrade_img: 'cat9k_iosxe.16.09.04.SPA.bin' 
    region: west
    vlans:
      - 101
      - 102
      - 103
      - 111
      - 201
      - 202
      - 203