---
username: admin
password: cisco
platform: ios
connection_options:
  netmiko:
    platform: cisco_ios
    extras:
      session_log: logs/netmiko_log.txt
  napalm:
    extras:
      optional_args:
        session_log: logs/napalm_log.txt
        global_delay_factor: 3
        max_loops: 1000
port: 22
data:
  acl:
    - remark: SRC_1
      entries:
      - 101.101.101.0 0.0.0.255
      - 101.101.111.0 0.0.0.255
    - remark: SRC_2
      entries:
      - 202.202.202.0 0.0.0.255
      - 202.202.222.0 0.0.0.255
  mgmt_src: Vlan999
  snmpv2_key1: snmp123!
  snmpv2_key2: snmp123@
  snmp3_user: SNMPOp3rator
  snmpv3_view: SNMPView
  snmpv3_hash: hasthiskey
  ise_key: c1sc0123!
  ise_vip_a_name: ISE_A
  ise_vip_a_ip: 10.10.10.10
  ise_vip_a_psn1: 10.10.10.11
  ise_vip_a_psn2: 10.10.10.12
  ise_vip_b_name: ISE_B
  ise_vip_b_ip: 10.10.10.20
  ise_vip_b_psn1: 10.10.10.21
  ise_vip_b_psn2: 10.10.10.22
  ise_vip_c_name: ISE_C
  ise_vip_c_ip: 10.10.10.30
  ise_vip_c_psn1: 10.10.10.31
  ise_vip_c_psn2: 10.10.10.32
  ise_vip_d_name: ISE_D
  ise_vip_d_ip: 10.10.10.40
  ise_vip_d_psn1: 10.10.10.41
  ise_vip_d_psn2: 10.10.10.42